# Addressing the medication non-adherence problem using data that are collected over time

## Background about data collection

Clinical trials collect information about patients (e.g., age, sex, co-morbidity) before the randomization. These patient characteristics are often utilized to estimate treatment effect, e.g., to obtain a more patient characteristic-specific treatment effect (i.e., treatment effect on female-only patients), reduce bias in the analysis, or reduce some uncertainty or doubt about the treatment effect. 
In regular care or hospitals, however, administrative databases regularly collect additional information about patient's health over time (e.g., other disease status, visits to doctors, emergency visits, hospital admission records, medication, and diagnosis reports). These are the continuous monitoring data that are recorded. In the regular clinical trial, these are called post-randomization observations (measured after randomization), and often discarded from the analysis. This practice is particularly popular, because handling these large amounts of a continuous flow of data is hard, and analyzing them used to be even more challenging. 

## Why researcher should budget accordingly to collect patient information regularly

The regular clinical trials usually last for short-term (3-5 years), whereas pragmatic trials can go on for many more years (10-15 years), and the condition of the patients may change over the course of time, and incorporating more current information into the analysis should help us adequately understand who is benefiting from the use of the drugs in the long term, and under which circumstances these benefits can be maximized. Also, for chronic conditions, such as diabetes or multiple sclerosis, where patients are required to take treatments for many years, medication adherence (whether patients are taking prescribed medication) should be measured continuously. Considering this longitudinal information (i.e., information that is collected over time) in the analysis, we can better understand the health implication of taking versus not taking the treatment regularly. Results from analysis done with such longitudinal information will be more accurate and relevant for the patient and their treatment decision-makers. 

## Statistical development of longitudinal data analysis methods, and gap in research

Statisticians, in recent years, have shown that utilizing this post-randomization information can significantly benefit understanding reasons why some patients may be continuing, discontinuing, or switching the treatment. Statisticians have also developed methods that can use this longitudinal information to predict the tendency of a patient to be adherent to medication.  These methods are known as ‘inverse probability of adherence per-protocol’ methods, where researchers first estimate the probability of medication adherence in a given period, and then use this probabilistic information to estimate the effect of the treatment received correctly. These methods for analyzing data generally separate the patients into two groups: whether the patient sufficiently adhered to the prescribed treatment or not in a given period (say, monthly) during the follow-up. To determine whether a patient is sufficiently medication adherent, many researchers use an 80% cut-point, although this cut-point may vary depending on the disease area. Therefore, if a patient took 85% of the medication within a month, we would label that patient as being “adherent” for that month. On the other hand, if a patient took 70% of the medication within a month, we would label that patient as being “non-adherent” for that month. Based on these advanced statistical methods and updated (e.g., monthly) information about adherence pattern, analysts can refine the analysis to obtain a valid estimate after considering medication adherence patterns. However, although the statistical theories were developed, some of these methods relying on updated information have not been well-tested within the context of pragmatic trials. 

## Our research filling the gap

In our project, our aim is to investigate the usefulness of these advanced statistical methods in addressing our specific problem of non-adherence under a variety of realistic pragmatic trial settings, and how to get reasonable effects of the treatment received in a pragmatic trial. To assess these methods, we first mimicked or simulated data based on realistic pragmatic trial scenarios. Some examples include,  

a)	We considered different disease scenarios: 

I.	We considered a scenario when treatment adherence is affected by other conditions, e.g., whether a patient has access to healthcare or pharmacy. 

II.	We considered a scenario when treatment adherence is affected by new health events during the follow-up: e.g., other medications that the same patient has to take due to a newly diagnosed co-morbidity. 

III.	We considered a scenario when treatment adherence is not affected by other conditions during the follow-up:  e.g., say patient discontinues taking the medication because of a perceived effect of the treatment on health - ‘drug is not working’. 

IV.	What is the impact when access to healthcare or pharmacy is important for our analysis, but we have not measured that information at the data collection stage?
We investigated the above realistic scenarios, and analyzed the mimicked data. We concluded that the statistical methods described earlier, which can utilize post-randomization information, could provide us better treatment effect estimates in most scenarios of a pragmatic trial. That means, compared to convention methods used in clinical trials, these advanced statistical methods can provide us more reasonable estimates (i.e., with reduced biasing effect). We also showed that even if the researchers fail to measure some of the necessary information during the data collection stage, these advanced statistical methods are still able to better approximate the effect estimate, compared to convention methods used in clinical trials.

b)	We also consider a situation when the treated group (who are prescribed a new treatment) adheres to the treatment differently than the control group (who are prescribed an existing drug, or standard of care). For example, let us consider a study on diabetic patients where we are interested in the impact of exercise daily. A diabetic patient who is assigned to the “control group”, is supposed to take metformin drug 3 times a day but does no need to do any exercise during the day, and this person adheres to the prescribed dosage of the treatment. But another diabetic patient who is assigned to the “treatment group”, should take metformin drug 3 times a day with 1 hour of exercise, but the patient actually takes only 1 metformin per day, and continues with 1 hour of exercise. Would this difference in medication-taking pattern impact the analysis?
Generally speaking, if participants in the study mostly follow the prescription with occasionally missing a few days here and there,  statistical methods, that can utilize post-randomization information, usually perform a pretty good job in obtaining the treatment effect estimate. 

-	First, let us talk about what happens if both treatment arms have similar non-adherence patterns. Depending on the degree of non-adherence, the estimates from these methods may suffer. Say, for example, if the rate of non-adherence is moderate, say, 30% of the time patients deviate from the prescription, only a negligible bias is introduced. If the rate of non-adherence is very high, say over 60% of the time, then a noticeable amount of bias is induced. 
-	If we consider the situation when there exists a difference in medication-taking pattern in both arms, say if the rate of non-adherence for the treatment group is very high, say over 60% of the times, but the control group patients mostly adheres the treatment (say, only 30% of the times they do not adhere), then this would be a better situation than the case when both groups equally being non-adherent to the treatment.

c)	When patients visit the hospital or doctor’s office frequently or rarely? For example, what happens if a patient is required to visit regularly every year, versus every 6 months. If the visit frequency changes, can we still estimate the treatment effect?

When the patients interact with the health systems (e.g., visit to the clinic) less often, we do not get to measure the necessary information more often, and hence we have access to less frequent post-randomization information during the follow-up. When the visit frequencies are very low, then even the estimates obtained from the advanced statistical methods will not be reliable. We need more frequent information collection in order to get a better understanding of the treatment effect estimate. If the patients visit the clinic less often and the adherence patterns in both arms are different, then the results can be even less reliable. Particularly, we need a good flow of information about whether patients took the medication regularly. Otherwise, patients may fail to recall whether they followed the prescription closely if they visit ti the clinic less often. We should encourage researchers to take the initiative to collect patient information more often.

d)	We also considered additional scenarios. For example, what happens if we only include a small number of patients in a pragmatic trial? What happens if the disease outcome is rare? These investigations will help future researchers to determine how good these statistical methods are in a given trial with specific sample size.

## A demonstration of an application of our method

We also included a case study from the Lipid Research Clinics Coronary Primary Prevention Trial to show an application of our methods in a real dataset. This trial had a sample size of 3, 550, with nearly 80% of the subjects deviated from the randomization treatment group by the end of the follow-up. The case study assessed whether a long-term reduction of serum cholesterol in hypercholesterolemic men, initially free of coronary heart disease, would lead to a lesser incidence of coronary heard disease. In the original study, only a conventional method was used, which could not take proper consideration of adherence patters, and the results were biased. In the current work, we have analyzed the data in a proper way to address the non-adherence problem. This case study demonstrates real-world applications of the estimators under consideration to account for non-adherence.

