# Addressing the partial non-adherence problem

## Background

Randomized clinical trials are considered a gold standard for evaluating how effective a particular new drug is. In these trials, highly experienced investigators work with highly selected participants. Randomized clinical trials usually follow strict protocols or rules to measure medication adherence. However, one common criticism is that these results from randomized clinical trials may not be readily translated to the general patients who are treated in a real-world clinical practice setting. 

To attempt to generalize the trial results to a larger and more realistic population, pragmatic trials are conducted that mimic real-world clinical practice settings. In a regular clinical setting, medical staff could be less experienced, who are more likely to make mistakes in administering treatment. On a broader population, patients outside of the strict inclusion criteria (e.g., could be older age patients who are often not included in a randomized clinical trial) may experience different adverse effects, and patients may not adequately follow the prescribed guidelines for a medication or its dose. Pragmatic trials, therefore, aim to incorporate these more realistic scenarios regarding patient and caregiver behaviours better than a regular randomized clinical trial. In that sense, pragmatic clinical trials are a step towards patient-oriented research that can be useful in providing real-world evidence, filling the gaps between clinical trials and clinical practices, and can answer questions likely to be the most relevant for patients.

## Existing methods to deal with adherence

There is some literature and guidance on how to estimate treatment effect when some patients are fully adherent, and some patients are not adherent at all. However, in the real world, most patients are somewhere in the middle, e.g., partially adherence. That means, most of the patients start to take the treatment and then decided to discontinue it for various reasons. As per our review of the literature, the most conventional methods (e.g., intent-to-treat, principal stratification methods) utilized to handle the problem of partial adherence is to simply re-label ‘partially adherent’ participants as either ‘fully adherent’ (i.e., fully compliant) or ‘fully non-adherent’ (i.e., fully non-compliant). These conventional methods for analyzing clinical trial data generally separate the patients between two groups: whether the patient is fully adherent to the prescribed treatment or not. Therefore, if a patient took 100% of the medication during the follow-up, we would label that patient as being adherent. On the other hand, if a patient took no medication during the follow-up, we would label that patient as being non-adherent. If a patient took 70% of the medication during the follow-up, this is a patient who is partially compliant. Most patients fall in this category in reality. For these patients, analysts need to make decisions regarding whether to assign them to fully adherent versus fully non-adherent group, to be able to use the conventional methods. Recent research suggests that such artificial adherence group assignment leads to biased results and incorrect conclusions.

To mitigate the problem associate with strict dichotomization methods, other researchers proposed methods that required the collection of rigorous and detailed post-randomization information frequently during the follow-up (e.g., collection of adherence data every month). While those methods are useful, collecting such a regular flow of information during a long follow-up may not be practical or cost-effective in a real-world pragmatic trial setting, particularly for chronic diseases. For example, if patients are not interacting with the health system very often for chronic diseases, i.e., visiting a hospital or a doctor’s clinic less often, then gathering regular information may be difficult.

## Our methods development

For those scenarios, in this research, we have extended an existing approach (i.e., the principal stratification approach) to accommodate 3 medication adherence categories instead of 2. In our method, instead of assigning patients to fully adherent and fully non-adherent groups, we can also consider fully non-adherent, partially adherent, and fully adherent groups according to their medication adherence behavior. Using mimicked data analysis, we showed that the newly developed method can mitigate this longstanding partial adherence issue far better than the conventional approaches regarding bias and uncertainty in estimates. Just like any other statistical methods, our developed method also relies on some statistical assumptions. We have assessed a range of simulation or mimicked data settings, and explored the impact of failing to incorporate appropriate statistical assumptions or conditions in the analysis. 
As an example, we used a real dataset from a trial, which was designed to estimate the impact of attending a series of workshops (i.e., attending workshops were study interventions) for smoking cessation (i.e., study outcome) among individuals with psychotic disorders. But some patients attended all workshops (8 in total), some did not attend enough of them (less than 5), and some attended a few of them (between 5 and 7). Although in the original trial, they had three tiers of treatment adherence (full, partial, none), the researchers used conventional methods to analyze the data. However, they could not incorporate the partial adherence category properly. In our work, we applied our developed method to address the same problem, but now we were able to handle three tiers of treatment adherence in the analysis properly.

## Why our research is valuable in practical settings

As we have developed the statistical framework for our method, this method can be extended to more general settings where we have more than 3 categories of medication adherence; one such example could be the analysis of the following categories, if such measurements are possible: no adherence (say 0%), poor adherence (say, 1-34%), moderate adherence (say, 35-66%), high adherence (67-99%) and full adherence (100%). Our research also shows that future researchers should not artificially dichotomize adherence patterns using conventional methods, and encourages researchers to retain more adherence categories in the analysis to obtain better results using the methods that we developed.

