# Research Outputs

## Journal articles {-}

1.	Karim ME, Hossain MB, Can LOCF be a reasonable approach for addressing sparse measurement issues? An illustration from per-protocol analysis in pragmatic trials. Under review (Objective 1)
2.	Mosquera LK, Karim ME, Hossain MB. Finite Sample Properties of Inverse Probability of Adherence Weighted Estimator of the Per-protocol Effect for Sustained Treatment Strategies”. Under review (Objectives 1)
3.	Sanders E, Gustafson P, Karim ME “Incorporating Partial Adherence Into the Principal Stratification Analysis Framework”, Statistics in Medicine, published online: 20-April-2021, https://doi.org/10.1002/sim.8986 (Objective 2)

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New article in Statistics in Medicine: Incorporating partial <a href="https://twitter.com/hashtag/adherence?src=hash&amp;ref_src=twsrc%5Etfw">#adherence</a> into <a href="https://twitter.com/hashtag/PrincipalStratification?src=hash&amp;ref_src=twsrc%5Etfw">#PrincipalStratification</a> analysis framework <a href="https://twitter.com/ubcspph?ref_src=twsrc%5Etfw">@ubcspph</a> <a href="https://twitter.com/CHEOSNews?ref_src=twsrc%5Etfw">@CHEOSNews</a> <a href="https://twitter.com/BCSUPPORTUnit?ref_src=twsrc%5Etfw">@BCSUPPORTUnit</a> <a href="https://twitter.com/NSERC_CRSNG?ref_src=twsrc%5Etfw">@NSERC_CRSNG</a> <a href="https://twitter.com/hashtag/PatientOrientedResearch?src=hash&amp;ref_src=twsrc%5Etfw">#PatientOrientedResearch</a> <a href="https://twitter.com/hashtag/PragmaticTrial?src=hash&amp;ref_src=twsrc%5Etfw">#PragmaticTrial</a> <a href="https://twitter.com/hashtag/MethodsMatters?src=hash&amp;ref_src=twsrc%5Etfw">#MethodsMatters</a> <a href="https://twitter.com/hashtag/CausalInference?src=hash&amp;ref_src=twsrc%5Etfw">#CausalInference</a> <a href="https://t.co/ZkLMjy0owX">https://t.co/ZkLMjy0owX</a> <a href="https://t.co/60EdwwMloG">pic.twitter.com/60EdwwMloG</a></p>&mdash; Ehsan Karim (@ehsan7x) <a href="https://twitter.com/ehsan7x/status/1384703309131390981?ref_src=twsrc%5Etfw">April 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

4.	Sanders E, Gustafson P, Karim ME “Treatment effect estimate bounds resulting from assuming monotone compliance-response in a principal stratification approach”. Under review (Objective 2)
5.	Hossain MB, Mosquera LK, Karim ME. Analysis approaches to address treatment nonadherence in pragmatic trials with point-treatment settings: a simulation study. Under revision (Objective 3)
6.	Hossain MB, Karim ME. Key considerations for choosing a statistical method to deal with incomplete treatment adherence in pragmatic trials. Under revision. (Objective 3)


## Conference Proceeding {-}

1.	Hossain MB, Mosquera L, Karim ME. Performance of statistical methods to address treatment non-adherence in pragmatic clinical trials with point treatment settings: a simulation study. University of Toronto Journal of Public Health. 2021; 2(2). doi: https://doi.org/10.33137/utjph.v2i2.36762 (Objective 3)
2.	Mosquera LK, & Karim ME. (2021, February). ESPACOMP-20-040: Evaluating Adjusted Per-Protocol Effect Estimators in Pragmatic Trials to Address Treatment Non-Adherence. In International Journal Of Clinical Pharmacy (Vol. 43, No. 1, pp. 298-298). Netherlands: Springer. https://doi.org/10.1007/s11096-020-01213-y [[link](https://link.springer.com/article/10.1007%2Fs11096-020-01213-y#Sec106)] (Objective 1)
3.	Hossain MB, Karim ME. (2021, February). ESPACOMP-20-011: Comparison of statistical methods to address treatment nonadherence in pragmatic trials with only baseline covariate-measurements. In International Journal Of Clinical Pharmacy (Vol. 43, No. 1, pp. 298-298). Netherlands: Springer. https://doi.org/10.1007/s11096-020-01213-y [[link](https://link.springer.com/article/10.1007%2Fs11096-020-01213-y#Sec22)] (Objective 3)

## Theses by trainees {-}

1.	Sanders E. Incorporating Partial Adherence into the Principal Stratification Analysis Framework, Statistics, UBC, MSc thesis, 2019. https://dx.doi.org/10.14288/1.0380529 (Objective 2)
2.	Mosquera,L. Exploring inverse probability weighted per-protocol estimates to adjust for non-adherence using post-randomization covariates : a simulation study, Statistics, UBC, MSc thesis, 2020. https://dx.doi.org/10.14288/1.0392954 (Objectives 1)


## International Conference Presentations {-}

1.	Karim ME (joint work with Hossain MB) Implications of choosing different imputation methods while inferring about per-protocol effects of sustained treatment strategies, ESPACOMP Conference (Virtual conference), Seraing, Belgium; 21 Oct 2021. [[link](https://www.espacomp.eu/wp-content/uploads/2021/11/Programme_detailed_07_11.pdf)] (Objective 1)

<iframe width="560" height="315" src="https://www.youtube.com/embed/pm8OOlPh3MU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

2.	Hossain MB (joint work with Karim ME) Addressing differential medication non-adherence in pragmatic trials with point-treatment settings: a simulation study. 25th ESPACOMP Conference (Virtual conference), Seraing, Belgium; 21 Oct 2021. [[link](https://www.espacomp.eu/wp-content/uploads/2021/11/Programme_detailed_07_11.pdf)] (Objective 3)
3.	Hossain MB (joint work with Karim ME) Comparison of statistical methods to address treatment nonadherence in pragmatic trials with only baseline covariate-measurements. 24th ESPACOMP: International Society for Medication Adherence Conference (Virtual conference), Seraing, Belgium; 10 Nov 2020. (Objective 3)
4.	Mosquera LK (joint work with Karim ME) Evaluating Adjusted Per-Protocol Effect Estimators in Pragmatic Trials to Address Treatment Non-Adherence. 24th ESPACOMP: International Society for Medication Adherence Conference (Virtual conference), Seraing, Belgium; 10 Nov 2020. (Objective 1)
5.	Hossain MB (joint work with Karim ME) Review of statistical methods to address treatment nonadherence in the pragmatic trial context. 41st Annual Conference of the International Society for Clinical Biostatistics (ISCB), Kraków, Poland, August 18, 2020 [RP3.28] (Objective 3)
6.	Mosquera LK (joint work with Karim ME) Properties of Adjusted Per-Protocol Effect Estimators to Address Treatment Non-Adherence in Pragmatic Trials. 41st Annual Conference of the International Society for Clinical Biostatistics (ISCB), Kraków, Poland, August 18, 2020 [RP3.26] (Objective 1)
7.  Mosquera LK (joint work with Karim ME) Comparing instrumental variable and naive methods for estimating the causal effect of treatment in pragmatic trials with non-compliance, The 2019 Atlantic Causal Inference Conference (ACIC), Montreal, May, 2019 (Objective 1)


## National Conference Presentations {-}

1.	Sanders E (joint work with Gustafson P, Karim ME) Incorporating Partial Adherence into the Principal Stratification Analysis Framework, Annual Meeting of the Statistical Society of Canada, Calgary, May, 2019 (Objective 2)
2.	Hossain MB (joint work with Karim ME) Comparing methods to address sparse follow-up issues in estimating per-protocol effects in pragmatic clinical trials: a simulation study. The ninth annual Canadian Statistics Student Conference (Virtual conference), Ottawa, Canada; 26 May 2021 (Objective 1) [Poster](https://drive.google.com/file/d/1s7f0ZbGF4TjnW4WVjy6mkPKovsxoW1oe/view) [Vodeo](https://drive.google.com/file/d/15Cz9Dwup6fc407AbeEJ5TNUxZ6IY_AK4/view)
3.	Hossain MB (joint work with Karim ME) Statistical approaches to deal with treatment nonadherence in the pragmatic trial context. Canadian Statistics Student Conference 2020 (Virtual conference), Ottawa, Canada; 30 May 2020. (Objective 3) 

<iframe width="560" height="315" src="https://www.youtube.com/embed/SZYp0aSz8Y4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

4.	Hossain MB (joint work with Karim ME) Comparing statistical methods in estimating per-protocol effects to address sparse follow-up issue in pragmatic clinical trials with treatment non-adherence. 6th Canadian Conference in Applied Statistics (Virtual conference), Montreal, Canada; 15 May 2021 (Objective 1)

<iframe width="560" height="315" src="https://www.youtube.com/embed/fZL5mRhvLqs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Workshop and Seminar Presentations {-}

1.	Hossain MB (joint work with Karim ME) Performance of statistical methods to address treatment non-adherence in pragmatic clinical trials with point-treatment settings: a simulation study. 2021 SORA-TABA Annual Workshop & DLSPH Biostatistics Research Day, May 27-28, 2021, Online. (Objective 3)
2.	Sanders E (joint work with Gustafson P, Karim ME) Incorporating Partial Adherence into the Principal Stratification Analysis Framework, Statistics Seminar, Department of Statistics, University of British Columbia, August 15, 2019. (Objective 2)


## Lay Summaries {-}

-	Ehsan Karim & RWCT–002 collaborators (2021) Developing and Evaluating Causal Inference Methods for Pragmatic Trials. https://ehsanx.github.io/Causal-Inference-Methods-for-Pragmatic-Trials/   (this website)

