--- 
title: "Developing and Evaluating Causal Inference Methods for Pragmatic Trials"
author: "Ehsan Karim & RWCT–002 collaborators"
date: ""
site: bookdown::bookdown_site
output:
  bookdown::html_document2:
    includes:
      in_header: header.html
      css: [style.css]
  bookdown::gitbook:
    includes:
      in_header: header.html
  bookdown::pdf_book:
    includes:
      in_header: header.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ehsanx/Causal-Inference-Methods-for-Pragmatic-Trials
description: "Causal Inference Methods for Pragmatic Trials."
header-includes: 
  - \usepackage{tcolorbox}
  - \newtcolorbox{blackbox}{colback=black,colframe=orange,coltext=white,boxsep=5pt,arc=4pt}
  - \usepackage{color}
  - \usepackage{framed}
  - \setlength{\fboxsep}{.8em}
---

\newenvironment{blackbox}{
  \definecolor{shadecolor}{rgb}{0, 0, 0}  % black
  \color{white}
  \begin{shaded}}
 {\end{shaded}}

# Overview

Although clinical trials are considered to be the gold standard for estimating the treatment effectiveness, the results of these trials are often not generalizable. Pragmatic trials include a broader range of subjects, who receive the treatment in everyday clinical practice in a real-world usual care scenario; and are much more representative than those selected for a regular clinical trial. In the pragmatic trials, as in the usual care scenario, patients can deviate from the protocol, e.g., they may not be adherent to the treatment they were assigned at the beginning of the trial, they may switch treatment, discontinue as people do in a real-world setting. Consequently, analyzing the datasets from these pragmatic trials require properly accounting for patients based on whether they have actually received the treatment or not; and hence analysis strategies need to be updated and developed accordingly. The simplistic analysis strategies of clinical trials are often inadequate in the presence of treatment non-adherence. Our project has developed and evaluated methods for promoting causal inference in analyzing pragmatic trial data. Patients and researchers will benefit from these research outcomes, as we have outlined which methods are appropriate to analyze a variety of clinical settings where non-adherence or partial adherence exists in pragmatic trials. Appropriately analyzing the pragmatic trials will inform healthcare professionals, patients, and other stakeholders about the implication of taking that treatment from an evidence-based approach; and the conclusions from these pragmatic trials are more suitable and relevant for health care decision-makers and patients.

Below is a technical overview prepared for the methods cluster at the beginning of the project, back in 2018:
<iframe width="560" height="315" src="https://www.youtube.com/embed/ur1etAewqHA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Three [trainees](https://ehsank.com/supervision/) helped in conducting research, manuscript writing, presenting research in national and international conferences:

- Md Belal Hossain (SPPH UBC) 
- Lucy Mosquera (Statistics UBC) 
- Eric Sanders (Statistics UBC) 

and a patient partner was recruited for reviewing lay summaries and providing feedback.

## Objectives {-}

In this project, we have address some of the methodological issues underlying the suitability of some of the methods already proposed in the literature to tackle generalizability of findings associated with non-adherence to medication as outlines in the protocol, and how to enhance those methods for the settings that are more reflective of real-world settings. 

- **Objective 1**. To assess the suitability of ‘g-methods’ in addressing non-adherence under various realistic pragmatic trial settings when some of the post-randomization predictor values are missing. 
- **Objective 2**. To estimate the ‘patient-oriented effect’ considering various types of adherence in the estimation process. 
- **Objective 3**. To compare various instrumental variable-based estimators to address non-adherence.


## Lay summaries {-}

-	While analyzing pragmatic trials datasets, not addressing incomplete treatment adherence can lead to biased treatment effect estimates. Sophisticated statistical methods are recently being developed, but often these methods are not well understood or accessible to the analysts. In this work, we have evaluated these methods and contrasted their performances with some of the commonly used methods under different realistic clinical settings. One particular challenging setting is when lab tests of the patients are done infrequently, and we have evaluated various missing data analysis techniques to address such challenges.

-	There is some analytical guidance on how to estimate treatment effects when some patients are fully adherent, and some patients are not adherent at all (2 categories of adherence). However, in the real world, most patients are partially adherence. That means most patients start to take the treatment and then may decide to discontinue it for various reasons. Our research has extended the existing analytic approach to accommodate patients who may partially adhere to the treatment  (e.g., considering a third category of adherence).

-	For dealing with medication non-adherence, a few methods are proposed in the econometric literature (e.g., popularly known as instrumental variable analysis). However, it is currently unknown how good those econometric methods are compared to the statistical methods (as mentioned above) if we apply them in the same context, focusing on pragmatic trials. In our project, we explored the characteristics of both of these methods and determined how useful these methods are in various clinical scenarios.

## Funding {-}

```{block, type='rmdcomment'}
BC SUPPORT (Support for People and Patient-Oriented Research and Trials) Unit Real World Clinical Trials (RWCT) Methods Cluster Project (RWCT – 002;  [Overview](https://members.bcsupportunit.ca/methods-clusters/webinars); [Description of the cluster projects](https://www.youtube.com/watch?v=B82TTE6v7Eg)).
```

## Contact {-}

For any questions or comments, please [contact](https://ehsank.com/) the lead of the project directly.
